name: publish executable file to release page
on:
  push:
    tags:
    - "v*"
  workflow_dispatch:

env:
  APP_NAME: ${{ github.event.repository.name }}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Clone PyInstaller, Build Bootloader and Install
        shell: cmd
        run: |
          python -m pip install --upgrade -r requirements.txt pip wheel
          git clone https://github.com/pyinstaller/pyinstaller.git --depth 1
          cd pyinstaller\bootloader
          python waf configure --msvc_targets=x86_64 build install
          cd ..
          pip install .

      - name: set version
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
              $ver = "${{ github.ref_name }}" -replace 'v', ''
          } else {
              $ver = "test"
          }
          Write-Output "VERSION=$ver" >> "$env:GITHUB_ENV"

      - name: Create executable file with pyinstaller and zip
        run: |
          pyinstaller "${env:APP_NAME}.py" `
            "--onefile" `
            "--noconsole" `
            "--icon=Assets/sample.ico" `
            "--exclude-module=PIL.ImageCms" `
            "--exclude-module=PIL.ImageMath" `
            "--exclude-module=PIL.ImageMorph" `
            "--exclude-module=PIL.ImageTk" `
            "--exclude-module=PIL._avif" `
            "--exclude-module=PIL._imagingcms" `
            "--exclude-module=PIL._imagingft" `
            "--exclude-module=PIL._imagingmath" `
            "--exclude-module=PIL._imagingtk" `
            "--exclude-module=PIL._webp" `
            "--exclude-module=_bz2" `
            "--exclude-module=_decimal" `
            "--exclude-module=_lzma" `
            "--exclude-module=_queue" `
            "--add-data=Assets/version.txt;Assets" `
            "--add-data=Assets/sample.ico;Assets"
          pushd dist
          Compress-Archive -Path "${env:APP_NAME}.exe" -DestinationPath "${env:APP_NAME}-${{ env.VERSION }}.zip"
          popd

      - name: Upload a executable file to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ env.APP_NAME }}-${{ env.VERSION }}.zip
